using Pettle.Domain.Bookings;
using Pettle.Domain.Common;

namespace Pettle.Domain.DailyTasks;

/// <summary>
/// One row per (date × booking-service × task-type) for the Daily Tasks board (FR-DT).
/// Default rows are auto-generated by DailyTaskService.EnsureEntriesAsync when the page is opened.
/// </summary>
public class DailyTaskEntry : TenantEntity
{
    public Guid BookingServiceId { get; set; }
    public BookingService? BookingService { get; set; }

    public DateOnly Date { get; set; }
    public DailyTaskType TaskType { get; set; }

    /// <summary>Free-text label, e.g. "8:00 AM meal", "Anti-rabies dose"; falls back to TaskType.ToString() when null.</summary>
    public string? Label { get; set; }

    public DailyTaskStatus Status { get; set; } = DailyTaskStatus.Pending;

    public DateTimeOffset? CompletedAt { get; set; }
    public Guid? CompletedByUserId { get; set; }
    public string? CompletedByName { get; set; }

    public string? Notes { get; set; }
    public string? PhotoUrl { get; set; }
}

public enum DailyTaskType
{
    Meal1 = 0,
    Meal2 = 1,
    Meal3 = 2,
    Meal4 = 3,
    Medication = 10,
    Walk1 = 20,
    Walk2 = 21,
    GroomingStep = 30,
    VetRound = 40,
    Note = 90,
    Custom = 99
}

public enum DailyTaskStatus
{
    Pending = 0,
    Done = 1,
    Skipped = 2
}
